/*
 * This file is generated by jOOQ.
 */
package com.godov.crudskyweaver.domain.jooq;


import com.godov.crudskyweaver.domain.jooq.tables.Matches;
import com.godov.crudskyweaver.domain.jooq.tables.Players;
import com.godov.crudskyweaver.domain.jooq.tables.records.MatchesRecord;
import com.godov.crudskyweaver.domain.jooq.tables.records.PlayersRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MatchesRecord> PK_MATCHES_ID = Internal.createUniqueKey(Matches.MATCHES, DSL.name("pk_matches_id"), new TableField[] { Matches.MATCHES.ID }, true);
    public static final UniqueKey<PlayersRecord> PK_PLAYERS_ADDRESS = Internal.createUniqueKey(Players.PLAYERS, DSL.name("pk_players_address"), new TableField[] { Players.PLAYERS.POLYGON_ADDRESS }, true);
    public static final UniqueKey<PlayersRecord> UNIQUE_NICKNAME = Internal.createUniqueKey(Players.PLAYERS, DSL.name("unique_nickname"), new TableField[] { Players.PLAYERS.NICKNAME }, true);
}
