/*
 * This file is generated by jOOQ.
 */
package com.godov.crudskyweaver.domain.jooq;


import com.godov.crudskyweaver.domain.jooq.tables.Matches;
import com.godov.crudskyweaver.domain.jooq.tables.Players;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.matches</code>.
     */
    public static final Matches MATCHES = Matches.MATCHES;

    /**
     * The table <code>public.players</code>.
     */
    public static final Players PLAYERS = Players.PLAYERS;
}
