/*
 * This file is generated by jOOQ.
 */
package com.godov.crudskyweaver.domain.jooq.enums;


import com.godov.crudskyweaver.domain.jooq.Public;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum HeroEnum implements EnumType {

    ADA("ADA"),

    LOTUS("LOTUS"),

    SAMYA("SAMYA"),

    BOURAN("BOURAN"),

    ARI("ARI"),

    TITUS("TITUS"),

    FOX("FOX"),

    HORIK("HORIK"),

    IRIS("IRIS"),

    ZOEY("ZOEY"),

    AXEL("AXEL"),

    SITTY("SITTY"),

    BANJO("BANJO"),

    MIRA("MIRA"),

    MAI("MAI");

    private final String literal;

    private HeroEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "hero_enum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static HeroEnum lookupLiteral(String literal) {
        return EnumType.lookupLiteral(HeroEnum.class, literal);
    }
}
