/*
 * This file is generated by jOOQ.
 */
package com.godov.crudskyweaver.domain.jooq.enums;


import com.godov.crudskyweaver.domain.jooq.Public;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ResultEnum implements EnumType {

    WIN("WIN"),

    LOSE("LOSE"),

    DRAW("DRAW");

    private final String literal;

    private ResultEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "result_enum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static ResultEnum lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ResultEnum.class, literal);
    }
}
